################################
#   Author: Salah Ud Din       #
#   GitHUb: @4yub1k            #
################################

# Main.py file generated by New Project wizard

# Created:   Sun Aug 20 2023
# Processor: RPI3
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource

# Peripheral Configuration Code (do not edit)
# ---CONFIG_BEGIN---
import cpu
import FileStore
import VFP


def peripheral_setup():
    # Peripheral Constructors
    pio.cpu = cpu.CPU()
    pio.storage = FileStore.FileStore()
    pio.server = VFP.VfpServer()
    pio.storage.begin()
    pio.server.begin(0)


# Install interrupt handlers


def peripheral_loop():
    pio.server.poll()


# ---CONFIG_END---
import RPi.GPIO as GPIO
import time
import asyncio

from mcp3008 import MCP3008
from lcd import LCD

GPIO.setmode(GPIO.BCM)
adc_mcp3008 = MCP3008(max_speed_hz=1_000_000)
lcd = LCD(5, 6, 12, 13, 16, 19)


def average(adc, channel_pin):
    sum_voltage = 0
    for i in range(50):
        value = adc.read_channel(channel=channel_pin)
        sum_voltage += value * (3.3 / 1023.0) * 131.793
    return sum_voltage / 50

lcd.cursor_start(0, 1)
lcd.print_line("GitHub: @4yub1k")

lcd.cursor_start(0, 0)
lcd.rotate_line("--- Author: Salah Ud Din ---")

while True:

    voltage_r = average(adc_mcp3008, 0)
    voltage_y = average(adc_mcp3008, 1)
    voltage_b = average(adc_mcp3008, 2)

    lcd.cursor_start(0, 0)
    lcd.print_line(f"R={voltage_r:.2f}Y={voltage_y:.2f}")  # "Message string
    lcd.cursor_start(4, 1)
    lcd.print_line(f"B={voltage_b:.2f}")

    time.sleep(1)
